
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.player
{
public sealed partial class PlayerPropertyConfig : Luban.BeanBase
{
    public PlayerPropertyConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["profession"].IsString) { throw new SerializationException(); }  Profession = _buf["profession"]; }
        { if(!_buf["hitPoint"].IsNumber) { throw new SerializationException(); }  HitPoint = _buf["hitPoint"]; }
        { if(!_buf["meleeDamage"].IsNumber) { throw new SerializationException(); }  MeleeDamage = _buf["meleeDamage"]; }
        { if(!_buf["meleeSpeed"].IsNumber) { throw new SerializationException(); }  MeleeSpeed = _buf["meleeSpeed"]; }
        { if(!_buf["meleeRange"].IsNumber) { throw new SerializationException(); }  MeleeRange = _buf["meleeRange"]; }
        { if(!_buf["temporaryHitPoint"].IsNumber) { throw new SerializationException(); }  TemporaryHitPoint = _buf["temporaryHitPoint"]; }
        { if(!_buf["vitality"].IsNumber) { throw new SerializationException(); }  Vitality = _buf["vitality"]; }
        { if(!_buf["recoverTime"].IsNumber) { throw new SerializationException(); }  RecoverTime = _buf["recoverTime"]; }
        { if(!_buf["recoverEfficiency"].IsNumber) { throw new SerializationException(); }  RecoverEfficiency = _buf["recoverEfficiency"]; }
        { if(!_buf["manaPoint"].IsNumber) { throw new SerializationException(); }  ManaPoint = _buf["manaPoint"]; }
        { if(!_buf["manaShield"].IsNumber) { throw new SerializationException(); }  ManaShield = _buf["manaShield"]; }
        { if(!_buf["activationTime"].IsNumber) { throw new SerializationException(); }  ActivationTime = _buf["activationTime"]; }
        { if(!_buf["fixEfficiency"].IsNumber) { throw new SerializationException(); }  FixEfficiency = _buf["fixEfficiency"]; }
        { if(!_buf["walkSpeed"].IsNumber) { throw new SerializationException(); }  WalkSpeed = _buf["walkSpeed"]; }
        { if(!_buf["runSpeed"].IsNumber) { throw new SerializationException(); }  RunSpeed = _buf["runSpeed"]; }
        { if(!_buf["jumpHeight"].IsNumber) { throw new SerializationException(); }  JumpHeight = _buf["jumpHeight"]; }
        { if(!_buf["diveSpeed"].IsNumber) { throw new SerializationException(); }  DiveSpeed = _buf["diveSpeed"]; }
        { if(!_buf["swimSpeed"].IsNumber) { throw new SerializationException(); }  SwimSpeed = _buf["swimSpeed"]; }
        { if(!_buf["fastSwimSpeed"].IsNumber) { throw new SerializationException(); }  FastSwimSpeed = _buf["fastSwimSpeed"]; }
    }

    public static PlayerPropertyConfig DeserializePlayerPropertyConfig(JSONNode _buf)
    {
        return new player.PlayerPropertyConfig(_buf);
    }

    /// <summary>
    /// 职业id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 职业备注
    /// </summary>
    public readonly string Profession;
    /// <summary>
    /// 生命
    /// </summary>
    public readonly int HitPoint;
    /// <summary>
    /// 近战伤害
    /// </summary>
    public readonly int MeleeDamage;
    /// <summary>
    /// 近战间隔(s)
    /// </summary>
    public readonly float MeleeSpeed;
    /// <summary>
    /// 近战范围(m)
    /// </summary>
    public readonly float MeleeRange;
    /// <summary>
    /// 临时生命
    /// </summary>
    public readonly int TemporaryHitPoint;
    /// <summary>
    /// 耐力(格)
    /// </summary>
    public readonly int Vitality;
    /// <summary>
    /// 耐力恢复时间(s)
    /// </summary>
    public readonly float RecoverTime;
    /// <summary>
    /// 耐力恢复速率(格/s)
    /// </summary>
    public readonly float RecoverEfficiency;
    /// <summary>
    /// 电力
    /// </summary>
    public readonly int ManaPoint;
    /// <summary>
    /// 电能护盾(格)
    /// </summary>
    public readonly int ManaShield;
    /// <summary>
    /// 充能激发时间(s)
    /// </summary>
    public readonly float ActivationTime;
    /// <summary>
    /// 充能效率(格/s)
    /// </summary>
    public readonly float FixEfficiency;
    /// <summary>
    /// 行走速度(m/s)
    /// </summary>
    public readonly float WalkSpeed;
    /// <summary>
    /// 疾跑速度(m/s)
    /// </summary>
    public readonly float RunSpeed;
    /// <summary>
    /// 跳跃高度(m)
    /// </summary>
    public readonly float JumpHeight;
    /// <summary>
    /// 下沉速度(m/s)
    /// </summary>
    public readonly float DiveSpeed;
    /// <summary>
    /// 游泳速度(m/s)
    /// </summary>
    public readonly float SwimSpeed;
    /// <summary>
    /// 加速游泳速度(m/s)
    /// </summary>
    public readonly float FastSwimSpeed;
   
    public const int __ID__ = 2076188613;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "profession:" + Profession + ","
        + "hitPoint:" + HitPoint + ","
        + "meleeDamage:" + MeleeDamage + ","
        + "meleeSpeed:" + MeleeSpeed + ","
        + "meleeRange:" + MeleeRange + ","
        + "temporaryHitPoint:" + TemporaryHitPoint + ","
        + "vitality:" + Vitality + ","
        + "recoverTime:" + RecoverTime + ","
        + "recoverEfficiency:" + RecoverEfficiency + ","
        + "manaPoint:" + ManaPoint + ","
        + "manaShield:" + ManaShield + ","
        + "activationTime:" + ActivationTime + ","
        + "fixEfficiency:" + FixEfficiency + ","
        + "walkSpeed:" + WalkSpeed + ","
        + "runSpeed:" + RunSpeed + ","
        + "jumpHeight:" + JumpHeight + ","
        + "diveSpeed:" + DiveSpeed + ","
        + "swimSpeed:" + SwimSpeed + ","
        + "fastSwimSpeed:" + FastSwimSpeed + ","
        + "}";
    }
}
}

