
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.player
{
public partial class TbProperty
{
    private readonly System.Collections.Generic.Dictionary<int, player.PlayerPropertyConfig> _dataMap;
    private readonly System.Collections.Generic.List<player.PlayerPropertyConfig> _dataList;
    
    public TbProperty(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, player.PlayerPropertyConfig>(count);
        _dataList = new System.Collections.Generic.List<player.PlayerPropertyConfig>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            player.PlayerPropertyConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.player.PlayerPropertyConfig.DeserializePlayerPropertyConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, player.PlayerPropertyConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<player.PlayerPropertyConfig> DataList => _dataList;

    public player.PlayerPropertyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public player.PlayerPropertyConfig Get(int key) => _dataMap[key];
    public player.PlayerPropertyConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

